gonum/optimize

unconstrained_test.go

Implemented all the functions, except for Chebyquad.

Add test functions from More, Garbow, Hillstrom (1981)

---

errors.go
termination.go
types.go
unconstrained_test.go

* Mistyped type names in comments
* Dots at the end of error strings
* Replace -= 1 with --

Fix some golint warnings

---

unconstrained_test.go

Fix breakage cause by mat64/blas64/blas restructuring.

Drop mat64.Register call

---

local.go

Move f/g call stats to evaluate()

---

local.go

Use evaluate() in getStartingLocation()

---

local.go

The first step towards fixing `Local()`, `minimize()` and `Linesearch`. I tried to keep the changes limited to `Local()`, but it was not possible everywhere.
Summary of changes:
* Put various initializations into a more reasonable order, so that things are initialized only when necessary.
* Properly record the starting location.
* Check the starting location for convergence before calling `minimize()`
* Check the initial function status if it is a `Statuser`
* Reduce the number of arguments to `minimize()`
* `getStartingLocation()` now also returns `EvaluationType` that was used at `initX`
* Add implementation comments to `Local()`

Rewrite Local()

---

doc.go

Add a short package description.

---

local.go
printer.go
types.go

... and modify update(), checkConvergence() and Printer to correctly
handle it.
Resolves #54.

Add InitIteration iteration type.

---

functions/functions.go
functions/functions_test.go
functions/validate.go

* Created testopt subpackage
* Copied objective functions from unconstrained_test.go
* Improved their documentation
* Most importantly, added tests that revealed mistakes in four functions. http://people.sc.fsu.edu/~jburkardt/m_src/test_opt/test_opt.html was used as a reference implementation
* Functions now return a list of their known minima
Modifying unconstrained_test.go to actually use these new, fairly reliably correct functions will come in another PR.

Add testopt, a testing subpackage

---

functions/functions.go

Used MINPACK-2 as a reference implementation.

Fix GulfResearchAndDevelopment function

---

unconstrained_test.go

Also, reduce the set of tests for CG in order to reduce the time needed
for 'go test' to finish.

Update unconstrained tests to use the functions subpackage

---

cg.go

Failure to generate a descent direction near a minimum is common for CG, however, the current implementation sometimes fails to generate a descent direction even when far from the minimum. This PR tries to fix it by restarting CG whenever a non-descent direction is generated. With this fix the test for the Box3D function in the other PR could be enabled.

Make sure CG always returns a descent direction

---

types.go

Also, fix and reformat comment for resize().
Closes #42

Update and Go-ify docs for Settings.

---

errors.go
linesearch.go
unconstrained_test.go

Fix infinite loop when Linesearch cannot make progress.

---

local.go
types.go
unconstrained_test.go

#84 should be reviewed and merged first.

Add Hessian to (F|f)unctionInfo

---

local.go
types.go

#84 and #85 should be reviewed and merged first.

Add Hessian to Location

---

backtracking.go
bfgs.go
bisection.go
cg.go
gradientdescent.go
interfaces.go
lbfgs.go
linesearch.go
local.go
neldermead.go
newton.go
printer.go
types.go
unconstrained_test.go

My interpretation of Issue 102. Comments and criticism welcome.

Switch from interfaces to Problem struct

---

bfgs.go

Update BFGS to changes in RankTwo() and SymRankOne()

---

bfgs.go

There is now a MulVec. Use it.

Change BFGS to use vectors instead of matrices.

---

backtracking.go
bisection.go
interfaces.go
linesearch.go

* Removes `Linesearcher.Finished()`
* Changes the order of return values from `Linesearcher.Iterate()`. Operation is the main value returned, so put it first.
* Slightly cleans up `Backtracking` and `Bisection`
* And tries to update the docs for `Linesearcher` ...
@btracey Please take a look

Remove Linesearcher.Finished()

---

functions/functions.go
functions/minsurf.go
functions/minsurf_test.go
functions/validate.go
local.go
types.go
unconstrained_test.go

Swap arguments to Grad and Hess

---

errors.go

Replace Inf with infinite in errors

---

bfgs.go

Initialize only the upper half of the Hessian

---

local.go

Pass a copy of Location.X to evaluating routines
