gonum/optimize

- stepsizers.go
* Implemented the other initial step size strategy described in Nocedal&Wright
* In some CG implementations the formula is attributed to Shanno&Phua, but for consistence with QuadraticStepSize the type's name FirstOrderStepSize rather refers to how the step size is estimated. ShannoPhuaStepSize is an alternative name anyway.
* This strategy seems to generate step size that work better with CG than those generated by QuadraticStepSize
* #16 should be reviewed and merged first
> Add Shanno-Phua initial step size

- local.go
- types.go
Currently, evaluate() panics when `evalType == NoEvaluation`. Also, location.X is modified even when evalType is not supported and no evaluation takes place. This PR fixes both issues and improves the comment for evaluate().
> Handle NoEvaluation in evaluate()

- linesearch.go
- local.go
* Fixed a missing return in `evaluate()`
* `finishedF` is not needed, because `evaluate()` will not overwrite our location
* Removed `finished` and replaced with `nextIterType`.
* Those copy() on non-MinorIterations are not strictly necessary.
The current `go test` passes, but interestingly its runtime has increased slightly, from roughly 0.4s on my machine to 0.46s. I have not investigated the reason.
The updated tests in the other PR pass too.
> Return correct iteration types from Linesearch

- bisection.go
The original code for Bisection included a secondary check to the strong Wolfe conditions to see if the optmiization was finished. The idea was to help mitigate floating point noise and allow for stronger convergence to the gradient. Unfortunately, all this does is add complexity. The parameters are ad hoc, and trade off floating point noise for actual function modulation. For more complicated functions (especially concurrent ones) the noise will be higher, while other functions may have modulations that are very small. It is impossible to design a tradeoff that is good for all functions. Instead, keep the code simple. This also fixes issues with Bisection and the outer OptLoc disagreeing on the optimum location
> Remove extra check for conclusion of Bisection.

- backtracking.go
- bfgs.go
- bisection.go
- cg.go
- gradientdescent.go
- interfaces.go
- lbfgs.go
- linesearch.go
- local.go
- printer.go
- stepsizers.go
* `Location` variables were named `location`, `loc` and `l` at different places in optimize, which was confusing. So this PR unifies `Location` variables to be consistently `loc`.
* `LinesearchLocation` variables are renamed to `loc`, `lsLoc` or `initLoc`, depending on the context. 
* `Linesearch` receiver is renamed to `ls`, `l` seemed too short, especially when `Location`s were still `l` at some places.
* Redundant `[]float64` from `Df()` and `FDf()` are removed.
This PR is simple, but extensive, so it is better reviewed commit by commit.
Remaining inconsistencies:
* `direction` and `dir` (let's use `dir`)
* `initLoc`, `initX`, `currStep` ... vs. `xNext`, `fPrev`, `stepSizePrev`, ... (let's use the abbreviated adjective at the beginning, i.e., `nextX`, `prevF`, ...)
> Unify variable names

- errors.go
- local.go
- unconstrained_test.go
Bad initial gradient values cause the line searches to fail as the Wolfe conditions are never met. Test the initial gradient to make sure it is not NaN or Inf. While here, fix the GulfRD test which has a gradient that evaluates to NaN at the optimum location. This allows the test at the optimum to be re-enabled
> Test initial location for NaN or Inf gradient values.

- functions/functions.go
It appears that there was some mistake in Watson too, the CG tests waiting in the other PR now run considerably faster. Hopefully this will be the last mistake in functions to fix. PTAL, @btracey 
Used MINPACK-2 as a reference implementation.
> Fix Watson function.

- functions/minsurf.go
- functions/minsurf_test.go
The first truly interesting function to be added to functions subpackage. Taken from MINPACK-2 test problem collection, good for testing our medium/large-scale minimization capabilities (although the function itself does not seem to be difficult to minimize). We can also use it to decide at which problem dimension we should switch the default method from BFGS to LBFGS. And it is also a good example of how to implement non-trivial functions.
> Add MinimalSurface function

- backtracking.go
- bisection.go
- functions/functions.go
- functions/minsurf.go
- functions/minsurf_test.go
- functions/validate.go
- interfaces.go
- linesearch.go
- local.go
- printer.go
- types.go
- unconstrained_test.go
This PR is proposal how the existing function interfaces could be modified in order to better accomodate functions that can evaluate their Hessian. This prepares the way for an implementation of Newton's method.
At present an objective function can implement the following three methods:
```go
F() // function value
Df() // gradient
FDf() // function value and gradient
```
For the Hessian the natural progression would be
```go
DDf(hess *mat64.SymDense) // hessian
FDfDDf(x float64, grad []float64, hess *mat64.SymDense) // function value, gradient and hessian
```
which I don't like much. Moreover, there is no naming connection to the corresponding EvaluationType and values in Stats and Settings.
Alternatively, the Hessian method could be
```go
Hessian(hess *mat64.SymDense)
```
or
```go …
```
> Rename function interface

- interfaces.go
- local.go
- termination.go
- types.go
Included two commits from #82 and addressed points 1-3 from the discussion therein. PTAL, @btracey .
As I mentioned, we could consider renaming the four statuses so that their name matches the corresponding fields in Settings, e.g. `IterationLimit` to `MajorIterationsLimit`, `HessianEvaluationLimit` to `HessEvaluationsLimit`, ...
> Add Hessian interface

- local.go
This has been discussed before and I think that it is indeed better not to return NotTerminated status, just as you suggested @btracey .
> Don't return NotTerminated from minimize()

- interfaces.go
- local.go
- types.go
- unconstrained_test.go
* Added initial Hessian to Settings
* Changed how the initial location is constructed. The deep nesting in there is not nice and I'd like to get rid of it, but the idea is what matters to me at the moment: the initial function value is used always, but the gradient and Hessian only if they are not nil. If they are, evaluate() is called. If the user wanted to use Newton method on a solution obtained with other gradient-based method, this would be useful. The problem is that if the objective function does not implement methods that directly correspond to evaluation types, we could end up doing more computation than if we just ignored the initial data. We would be doing our best with what the user gave us, but the behaviour might still be slightly surprising and hard to document.
Seeing the …
> Add initial Hessian to Settings

- interfaces.go
- linesearch.go
- local.go
- types.go
- unconstrained_test.go
A quick, experimental implementation that deals with the problem of too many combinations of what method needs, what function can evaluate, what should be the next evaluation given the previous evaluation, etc.
* Gradient and Hessian interfaces are required if Method.Needs() indicates so
* FunctionGradient and FunctionGradientHessian are optional
* EvaluationTypes are ORable and any combination is acceptable
* loc.Gradient does not need to be allocated if method needs Hessian
* evaluate() is greatly simplified. If we removed the combined, optional interfaces completely, it could be even simpler.
* Adding constraints evaluation in the future would be straightforward
PTAL, @btracey
> ORable EvaluationTypes; required Gradient and/or Hessian interfaces

- bisection.go
- local.go
- printer.go
- types.go
PTAL, @btracey 
In the end I decided to format EvaluationType using your suggestion. Using just `EvaluationType(number)` would be also fine, because non-implementers of outside Methods would almost never get to see evaluation types default formatted, only possibly via Recorders. On the other hand, implementers of Methods could get to see a default-formatted evaluation type in a panic, in which case a better formatted information could be handy.
> Remove combined evaluation types

- functions/functions.go
Another PR that I'd like to review and merge before #99 so that tests for Newton can go in as a part of that PR.
I chose simple and low-dimensional functions (except for one) and I used MINPACK-2 as a reference implementation, so I believe the implementation should be correct.
I also slightly modified the known minimum for `BrownAndDennis` function. The function value is higher on the level of floating-point noise, but the norm of the gradient is lower than before. I remember that inaccurate locations of minima were forcing us to use loose tolerances for the norm of the gradient in the past.
> Add Hess() method to some test functions

- newton.go
- types.go
- unconstrained_test.go
Has the time really come for Newton?
An implementation of a pure, locally convergent Newton method without linesearch and of a modified, globally convergent Newton method with a linesearch.
The pure Newton is rather simple now that mat64 has symmetric matrices and Cholesky decomposition.
The modification in ModifiedNewton is a simple one, just add multiples of identity to the Hessian until it becomes positive definite. I did not venture into the modified Cholesky method at the moment but I can if there is a desire to have it.
I added three functions for resizing/reusing matrices in a similar way we already resize/reuse slices. Experts on matrix package @kortschak @btracey might have a better suggestion.
No tests at the moment, first we need to add Hess() method to functions, then modify …
> Add Newton method

- bfgs.go
mat64 changed so that Inner takes a *mat64.Vector instead of a []float64. Update BFGS to this new API
> Fix BFGS to have vector arguments in Inner.

- functions/minsurf.go
- functions/minsurf_test.go
When FunctionGradient interface was removed, MinimalSurface function was not updated. This PR fixes that. PTAL @btracey
> Update MinimalSurface to implement Gradient interface

- interfaces.go
- local.go
- printer.go
- types.go
* Make optimize silent by default
* Simplify Printer
* Change the printout format so that is is as fixed-width as possible for a majority of optimization runs.
* Remove FunctionInfo argument from Recorder.Init(). There is no reason why a Recorder should need information about the objective function for its initialization
PTAL @btracey
> Clean Printer and change Recorder interface

- backtracking.go
- bfgs.go
- bisection.go
- cg.go
- gradientdescent.go
- interfaces.go
- lbfgs.go
- linesearch.go
- local.go
- neldermead.go
- newton.go
- types.go
Discussion in #110 implies that `Method` cannot make any use of `ProblemInfo` which therefore becomes unnecessary.
PTAL, @btracey
> Remove unnecessary ProblemInfo

- backtracking.go
- bfgs.go
- bisection.go
- cg.go
- gradientdescent.go
- interfaces.go
- lbfgs.go
- linesearch.go
- newton.go
- types.go
- unconstrained_test.go
This is something I have wanted to do for some time now:
* `Linesearch.Init()` and `Linesearch.initNextLinesearch()` were both doing almost exactly the same thing. Now the former calls the latter.
* It is very unlikely that `Linesearch` could be used for a non-gradient-based optimization. Init() now panics, if `loc.Gradient == nil`, which makes the code simpler.
* Both `Linesearch.Iterate()` and `Linesearch.initNextLinesearch()` were slightly cleaned and improved, for example `evalType` and `iterType` are now both consistently updated.
* Docs for `Linesearch` were improved to make clear that it is just a helper struct, not a method in itself.
* I renamed `Linesearch` to `LinesearchHelper` and `LinesearchMethod` to `Linesearch`. As the commit message says:
> Linesearch is a too nice name …
> Clean and improve Linesearch code

- errors.go
I feel this is a more evocative name.
As an aside, it is not used anywhere. Is it actually needed?
@btracey @vladimir-ch Please take a look.
> optimize: rename ErrMismatch -> MethodMismatch

- newton.go
It is always used, so allocate it with the Newton struct.
@btracey Please take a look.
> optimize: make chol field concrete type

- backtracking.go
- bfgs.go
- bisection.go
- cg.go
- gradientdescent.go
- interfaces.go
- lbfgs.go
- linesearch.go
- local.go
- neldermead.go
- newton.go
- printer.go
- types.go
- unconstrained_test.go
A proposal for resolving #103 ~~but still work in progress~~.
* Merged `IterationType` and `EvaluationType` into ~~`RequestType`~~ `Operation`.
* Simplified `Method` interface. It can't be any simpler than this, so if this PR is accepted, further changes are very unlikely.
* The above two modifications ripple through the code and lead at some places to essentially a complete rewrite, most importantly in `LinesearchMethod` and `minimize()`. But the issue at hand is solved, and the code is now much cleaner and more correct. I am ~~quite~~ very happy with the changes (if nobody praises you, you must praise yourself).
* Updated docs, especially for `Method` and `Operation`, although while at it, I updated the docs also at other places, which, as a by-product, resolves issues #29 and #96. …
> Merge IterationType and EvaluationType, simplify Method interface

- cg.go
- functions/minsurf_test.go
- interfaces.go
- linesearch.go
- local.go
- termination.go
- types.go
- unconstrained_test.go
> Drop () from FuncName() in comments

- interfaces.go
- linesearch.go
- local.go
- neldermead.go
- types.go
* Stop invalidating in `evaluate()`
* Remove `LinesearchMethod.loc` and instead gradually build up a valid location from the passed `Location`. This avoids a lot of unnecessary copying and results in simpler code. It is a horribly crude benchmark, but on my machine `go test` finishes regularly in 7.8-7.9 s with this change which is roughly 0.5 s faster than before.
@btracey Please take a look
> Stop modifying Location beyond requested evaluations

- backtracking.go
- bisection.go
- errors.go
- linesearch.go
Closes #124, I went with `ErrNonDescentDirection`, "descent direction" seems more common than "decrease direction".
I also renamed `ErrLinesearchFailure` to `ErrLinesearcherFailure`, slightly updated some error comments and reordered them. 
In an effort towards stabilization of the API we should review the error variables. For example, ErrLinesearcherFailure seems too broad and not very descriptive.
PTAL @btracey
> Rename some error variables and update their comments

- errors.go
- local.go
Changes discussed in https://github.com/gonum/optimize/pull/136#issuecomment-143515739
@vladimir-ch @btracey Please take a look.
> optimize: make initialization errors hold their cause

- bfgs.go
I think that with mat64 the code is cleaner and clearer.
Also, don't update the inverse Hessian if `sDotY` is zero (to avoid division by zero).
@btracey @kortschak PTAL
> Use mat64 instead of floats in BFGS

- cg.go
Eventually I would like to replace floats with mat64 in all our Methods. In case of CG there is a small inconvenience because the previous gradient and direction, stored in CG as mat64.Vector, are passed to CGVariant.Beta as slices. Options:
1. Pass the slices from RawVector().Data and use floats in implementations of CGVariant (or wrap the slices again there). I don't like this much but it is what this PR does.
2. Change the CGVariant interface to take *mat64.Vector instead of slices.
3. Don't use mat64.Vector in CG.
I vote for 2. @btracey PTAL
> Use mat64 in CG

- lbfgs.go
> Clean up LBFGS

- cg.go
- errors.go
- functions/functions.go
- linesearcher_test.go
- morethuente.go
I like the names DecreaseFactor and CurvatureFactor. I would vote for using them also in the other Linesearchers.
As I mentioned before, CG is the method that most benefits from this Linesearcher, so I set it as the default. Maybe we should remake the CG tests, there are already many combinations and the Linesearchers add an extra dimension.
PTAL @btracey
> Add MoreThuente Linesearcher

- backtracking.go
- bisection.go
- linesearch.go
- linesearcher_test.go
- unconstrained_test.go
Also renamed `Decrease` to `Contraction` in `Backtracking`, not sure if it is a good name. PTAL @btracey
> Rename FuncConst and GradConst in linesearchers

- bisection.go
I looked into adding `DecreaseFactor` to `Bisection` as discussed in #155. I am not sure if the logic of iterating towards the minimum would work under all conditions with a positive `DecreaseFactor`. I think that it would consists of more than just modifying an `if` check and passing a non-zero to `StrongWolfeConditionsMet`. Quite possibly a two-stage approach like in `MoreThuente` would be needed. Therefore I abandon the plan for the moment.
So at least I did a tiny cleanup. PTAL @btracey
> Small clean-up in Bisection

- local_example_test.go
This CL adds a simple example, extracted from:
http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize
> optimize: add example for Local+BFGS
